[package]
name = "snm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7.1"
dioxus = "0.4.0"
dioxus-ssr = "0.4.0"
tokio = { version = "1.34.0", features = ["full"] }
